<a href="https://colab.research.google.com/github/OverGeek/Text-Generation/blob/master/Text_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DOWNLOADING DATASET**

In [0]:
from keras.utils.data_utils import get_file
path = get_file(
    'nietzsche.txt',
    origin='https://s3.amazonaws.com/text-datasets/nietzsche.txt')

Using TensorFlow backend.


In [0]:
import io
with io.open(path, encoding='utf-8') as f:
    text = f.read().lower()
print('corpus length:', len(text))

corpus length: 600893


In [0]:
s = ""
for i in range(10, len(text)):
  if text[i] == '\n':
    s += (' ')
  else:
    s += text[i]

In [0]:
text = s
text[:100]

'supposing that truth is a woman--what then? is there not ground for suspecting that all philosophers'

**PREPROCESSING DATA**

In [0]:
text.split(' ')[:100]

['supposing',
 'that',
 'truth',
 'is',
 'a',
 'woman--what',
 'then?',
 'is',
 'there',
 'not',
 'ground',
 'for',
 'suspecting',
 'that',
 'all',
 'philosophers,',
 'in',
 'so',
 'far',
 'as',
 'they',
 'have',
 'been',
 'dogmatists,',
 'have',
 'failed',
 'to',
 'understand',
 'women--that',
 'the',
 'terrible',
 'seriousness',
 'and',
 'clumsy',
 'importunity',
 'with',
 'which',
 'they',
 'have',
 'usually',
 'paid',
 'their',
 'addresses',
 'to',
 'truth,',
 'have',
 'been',
 'unskilled',
 'and',
 'unseemly',
 'methods',
 'for',
 'winning',
 'a',
 'woman?',
 'certainly',
 'she',
 'has',
 'never',
 'allowed',
 'herself',
 'to',
 'be',
 'won;',
 'and',
 'at',
 'present',
 'every',
 'kind',
 'of',
 'dogma',
 'stands',
 'with',
 'sad',
 'and',
 'discouraged',
 'mien--if,',
 'indeed,',
 'it',
 'stands',
 'at',
 'all!',
 'for',
 'there',
 'are',
 'scoffers',
 'who',
 'maintain',
 'that',
 'it',
 'has',
 'fallen,',
 'that',
 'all',
 'dogma',
 'lies',
 'on',
 'the',
 'ground--nay',
 'mor

In [0]:
print("Number of words:", len(text.split(' ')))

Number of words: 101140


In [0]:
unique_words = set(text.split(' '))
print('Number of unique words: ', len(unique_words))
unique_words = list(sorted(unique_words))

Number of unique words:  17682


In [0]:
unique_words[0:10]

['',
 '"=man',
 '"a',
 '"above',
 '"absolute',
 '"according',
 '"actually"',
 '"affliction"',
 '"ah,',
 '"all']

In [0]:
word_to_int = {}
int_to_word = {}
for index, word in enumerate(unique_words):
  word_to_int[word] = index
  int_to_word[index] = word

In [0]:
word_to_int.items()

dict_items([('', 0), ('"=man', 1), ('"a', 2), ('"above', 3), ('"absolute', 4), ('"according', 5), ('"actually"', 6), ('"affliction"', 7), ('"ah,', 8), ('"all', 9), ('"all,"', 10), ('"almost"', 11), ('"aloft"', 12), ('"among', 13), ('"ancient', 14), ('"and', 15), ('"another', 16), ('"anti-natural"', 17), ('"antique', 18), ('"arbitrarily,"', 19), ('"arduously"--that', 20), ('"are', 21), ('"arms', 22), ('"art"', 23), ('"as', 24), ('"at', 25), ('"atomistic', 26), ('"away', 27), ('"back,"', 28), ('"bad', 29), ('"bad!', 30), ('"bad"', 31), ('"bad":', 32), ('"bad,"', 33), ('"badly"--and', 34), ('"be', 35), ('"being-conscious"', 36), ('"being-in-itself"', 37), ('"being-in-itself,"', 38), ('"belief"', 39), ('"belief,"', 40), ('"believing', 41), ('"belong"', 42), ('"better', 43), ('"beyond', 44), ('"bible,"', 45), ('"big', 46), ('"birth', 47), ('"blood,"', 48), ('"book"!', 49), ('"born', 50), ('"box', 51), ('"break', 52), ('"business"--has', 53), ('"but', 54), ('"by', 55), ('"calculable"', 56), 

In [0]:
int_to_word.items()

dict_items([(0, ''), (1, '"=man'), (2, '"a'), (3, '"above'), (4, '"absolute'), (5, '"according'), (6, '"actually"'), (7, '"affliction"'), (8, '"ah,'), (9, '"all'), (10, '"all,"'), (11, '"almost"'), (12, '"aloft"'), (13, '"among'), (14, '"ancient'), (15, '"and'), (16, '"another'), (17, '"anti-natural"'), (18, '"antique'), (19, '"arbitrarily,"'), (20, '"arduously"--that'), (21, '"are'), (22, '"arms'), (23, '"art"'), (24, '"as'), (25, '"at'), (26, '"atomistic'), (27, '"away'), (28, '"back,"'), (29, '"bad'), (30, '"bad!'), (31, '"bad"'), (32, '"bad":'), (33, '"bad,"'), (34, '"badly"--and'), (35, '"be'), (36, '"being-conscious"'), (37, '"being-in-itself"'), (38, '"being-in-itself,"'), (39, '"belief"'), (40, '"belief,"'), (41, '"believing'), (42, '"belong"'), (43, '"better'), (44, '"beyond'), (45, '"bible,"'), (46, '"big'), (47, '"birth'), (48, '"blood,"'), (49, '"book"!'), (50, '"born'), (51, '"box'), (52, '"break'), (53, '"business"--has'), (54, '"but'), (55, '"by'), (56, '"calculable"'), 

In [0]:
l = text.split(' ')
l1 = [word_to_int[i] for i in l]
len(l1)

101140

In [0]:
import numpy as np
Tx = 70
X = []
for i in range(0, len(l1)-Tx, Tx):
  temp = []
  for j in range(i, i+Tx):
    temp.append(l1[j])
  X.append(temp)
X = np.array(X)

In [0]:
X.shape

(1444, 70)

In [0]:
m = X[0]
Tx = 70

In [0]:
import numpy as np
Tx = 70
Y = []
for i in range(1, len(l1)-Tx, Tx):
  temp = []
  for j in range(i, i+Tx):
    temp.append(l1[j])
  Y.append(temp)
Y = np.array(Y)

In [0]:
Y.shape

(1444, 70)

In [0]:
X[0]

array([15465, 15795, 16363,  9122,  1452, 17472, 15857,  9122, 15876,
       10996,  7576,  6921, 15525, 15795,  1845, 11944,  8514, 14673,
        6581,  2333, 15931,  7779,  2736,  5384,  7779,  6506, 16131,
       16521, 17482, 15807, 15765, 14284,  2006,  3661,  8467, 17439,
       17299, 15931,  7779, 16802, 11568, 15817,  1631, 16131, 16366,
        7779,  2736, 16695,  2006, 16689, 10303,  6921, 17405,  1452,
       17477,  3397, 14393,  7762, 10894,  1884,  7956, 16131,  2688,
       17487,  2006,  2442, 12451,  6143,  9323, 11201])

In [0]:
Y[0]

array([15795, 16363,  9122,  1452, 17472, 15857,  9122, 15876, 10996,
        7576,  6921, 15525, 15795,  1845, 11944,  8514, 14673,  6581,
        2333, 15931,  7779,  2736,  5384,  7779,  6506, 16131, 16521,
       17482, 15807, 15765, 14284,  2006,  3661,  8467, 17439, 17299,
       15931,  7779, 16802, 11568, 15817,  1631, 16131, 16366,  7779,
        2736, 16695,  2006, 16689, 10303,  6921, 17405,  1452, 17477,
        3397, 14393,  7762, 10894,  1884,  7956, 16131,  2688, 17487,
        2006,  2442, 12451,  6143,  9323, 11201,  5377])

**LABEL TO  ONE-HOT**

In [0]:
from keras.utils import to_categorical

Y = to_categorical(Y[:,:], num_classes = len(unique_words))
Y.shape

(1444, 70, 17682)

**BUILDING MODEL**

In [0]:
import keras
from keras.layers import Dense, Dropout, LSTM, Activation, Input
from keras.models import Model
from keras.layers.embeddings import Embedding

In [0]:
emb_matrix = np.zeros((len(unique_words)+1, 100))
emb_matrix.shape

(17683, 100)

In [0]:
embedding_layer = Embedding(len(unique_words)+1, 500, trainable = True, embeddings_initializer='uniform')
embedding_layer.build((None,))

In [0]:
def LSTM_model(input_shape):
    sentence_indices = Input(shape = input_shape, dtype = np.int32)
    embeddings = embedding_layer(sentence_indices)
    X = LSTM(256, return_sequences = True)(embeddings)
    X = Dropout(0.5)(X)
    X = LSTM(256, return_sequences = True)(X)
    X = Dropout(0.5)(X)
    X = LSTM(128, return_sequences = True)(X)
    X = Dropout(0.25)(X)
    X = Dense(len(unique_words), activation = 'softmax')(X)
    
    model = Model(inputs = sentence_indices, outputs = X)
    
    return model

In [0]:
model = LSTM_model((Tx,))

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 70)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 70, 500)           8841500   
_________________________________________________________________
lstm_1 (LSTM)                (None, 70, 256)           775168    
_________________________________________________________________
dropout_1 (Dropout)          (None, 70, 256)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 70, 256)           525312    
_________________________________________________________________
dropout_2 (Dropout)          (None, 70, 256)           0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 70, 128)           197120    
__________

In [0]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])


In [0]:
model.fit(X, Y, epochs = 100, batch_size = 32, shuffle = True)

Epoch 1/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.1462 - acc: 0.0609
Epoch 2/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.1023 - acc: 0.0610
Epoch 3/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0919 - acc: 0.0610
Epoch 4/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0888 - acc: 0.0610
Epoch 5/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0884 - acc: 0.0610
Epoch 6/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0876 - acc: 0.0610
Epoch 7/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0893 - acc: 0.0611
Epoch 8/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0877 - acc: 0.0610
Epoch 9/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0876 - acc: 0.0610
Epoch 10/100
1444/1444 [==============================] - 28s 19ms/step - loss: 7.0880 - acc: 0.0611

**CHARACTER LEVEL**

In [0]:
l = list(text)
len(l)

600883

In [0]:
unique_chars = list(sorted(set(l)))

In [0]:
len(unique_chars)

56

In [0]:
char_to_int = {}
int_to_char = {}
for i,c in enumerate(unique_chars, 0):
  char_to_int[c]=i
  int_to_char[i]=c

In [0]:
l1 = [char_to_int[i] for i in l]

In [0]:
l1[:10]

[44, 46, 41, 41, 40, 44, 34, 39, 32, 0]

In [0]:
len(l1)

600883

In [0]:
import numpy as np
Tx = 70
X = []
for i in range(0, len(l1)-Tx, Tx):
  temp = []
  for j in range(i, i+Tx):
    temp.append(l1[j])
  X.append(temp)
X = np.array(X)

In [0]:
X.shape

(8584, 70)

In [0]:
import numpy as np
Tx = 70
Y = []
for i in range(1, len(l1)-Tx, Tx):
  temp = []
  for j in range(i, i+Tx):
    temp.append(l1[j])
  Y.append(temp)
Y = np.array(Y)

In [0]:
Y.shape

(8584, 70)

In [0]:
X[0]

array([44, 46, 41, 41, 40, 44, 34, 39, 32,  0, 45, 33, 26, 45,  0, 45, 43,
       46, 45, 33,  0, 34, 44,  0, 26,  0, 48, 40, 38, 26, 39,  7,  7, 48,
       33, 26, 45,  0, 45, 33, 30, 39, 22,  0, 34, 44,  0, 45, 33, 30, 43,
       30,  0, 39, 40, 45,  0, 32, 43, 40, 46, 39, 29,  0, 31, 40, 43,  0,
       44, 46])

In [0]:
Y[0]

array([46, 41, 41, 40, 44, 34, 39, 32,  0, 45, 33, 26, 45,  0, 45, 43, 46,
       45, 33,  0, 34, 44,  0, 26,  0, 48, 40, 38, 26, 39,  7,  7, 48, 33,
       26, 45,  0, 45, 33, 30, 39, 22,  0, 34, 44,  0, 45, 33, 30, 43, 30,
        0, 39, 40, 45,  0, 32, 43, 40, 46, 39, 29,  0, 31, 40, 43,  0, 44,
       46, 44])

**LABEL TO ONE-HOT**

In [0]:
from keras.utils import to_categorical

Y = to_categorical(Y[:,:], num_classes = len(unique_chars))
print(Y.shape)
Y[0][0]

(8584, 70, 56)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.], dtype=float32)

**BUILDING MODEL**

In [0]:
import keras
from keras.layers import Dense, Dropout, LSTM, Activation, Input
from keras.models import Model
from keras.layers.embeddings import Embedding

In [0]:
embedding_layer = Embedding(len(unique_chars), 100, trainable = True, embeddings_initializer='uniform')
embedding_layer.build((None,))

In [0]:
def LSTM_model(input_shape):
    sentence_indices = Input(shape = input_shape, dtype = np.int32)
    embeddings = embedding_layer(sentence_indices)
    X = LSTM(256, return_sequences = True)(embeddings)
    X = Dropout(0.5)(X)
    X = LSTM(256, return_sequences = True)(X)
    X = Dropout(0.5)(X)
    X = LSTM(128, return_sequences = True)(X)
    X = Dropout(0.25)(X)
    X = Dense(len(unique_chars), activation = 'softmax')(X)
    
    model = Model(inputs = sentence_indices, outputs = X)
    
    return model

In [0]:
model = LSTM_model((70,))

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 70)                0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 70, 100)           5600      
_________________________________________________________________
lstm_1 (LSTM)                (None, 70, 256)           365568    
_________________________________________________________________
dropout_1 (Dropout)          (None, 70, 256)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 70, 256)           525312    
_________________________________________________________________
dropout_2 (Dropout)          (None, 70, 256)           0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 70, 128)           197120    
__________

In [0]:
from keras import optimizers
opt = optimizers.Adam(lr = 0.01)

model.compile(loss = 'categorical_crossentropy', optimizer = opt, metrics = ['accuracy'])


In [0]:
model.load_weights('save8_95epochs.h5')
model.fit(X, Y, epochs = 20, batch_size = 512, shuffle = True)

Epoch 1/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4623 - acc: 0.5533
Epoch 2/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4619 - acc: 0.5540
Epoch 3/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4614 - acc: 0.5540
Epoch 4/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4613 - acc: 0.5541
Epoch 5/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4615 - acc: 0.5546
Epoch 6/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4615 - acc: 0.5537
Epoch 7/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4605 - acc: 0.5551
Epoch 8/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4594 - acc: 0.5554
Epoch 9/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4594 - acc: 0.5553
Epoch 10/20
8584/8584 [==============================] - 10s 1ms/step - loss: 1.4579 - acc: 0.5552
Epoch 11/20
8584/85

In [0]:
model.save_weights('save9_105epochs.h5')

**Testing the model**

In [0]:
test = list(text[:70])
print(test)

['s', 'u', 'p', 'p', 'o', 's', 'i', 'n', 'g', ' ', 't', 'h', 'a', 't', ' ', 't', 'r', 'u', 't', 'h', ' ', 'i', 's', ' ', 'a', ' ', 'w', 'o', 'm', 'a', 'n', '-', '-', 'w', 'h', 'a', 't', ' ', 't', 'h', 'e', 'n', '?', ' ', 'i', 's', ' ', 't', 'h', 'e', 'r', 'e', ' ', 'n', 'o', 't', ' ', 'g', 'r', 'o', 'u', 'n', 'd', ' ', 'f', 'o', 'r', ' ', 's', 'u']


In [0]:
test = [char_to_int[i] for i in test]
print(test)

[44, 46, 41, 41, 40, 44, 34, 39, 32, 0, 45, 33, 26, 45, 0, 45, 43, 46, 45, 33, 0, 34, 44, 0, 26, 0, 48, 40, 38, 26, 39, 7, 7, 48, 33, 26, 45, 0, 45, 33, 30, 39, 22, 0, 34, 44, 0, 45, 33, 30, 43, 30, 0, 39, 40, 45, 0, 32, 43, 40, 46, 39, 29, 0, 31, 40, 43, 0, 44, 46]


In [0]:
test = np.array(test)

In [0]:
test.shape

(70,)

In [0]:
test = np.expand_dims(test, axis = 0)

In [0]:
test.shape

(1, 70)

In [0]:
prediction = model.predict(test)

In [0]:
prediction = prediction.reshape((70, 56))
prediction.shape

(70, 56)

In [0]:
preds = np.argmax(prediction, axis = 1)
print(preds)

[ 0 41 41 40 44 34 45 32  0 45 33 30 45  0 45 33 46 45 33  0 45 39  0 45
  0 41 40 43 26 39  0  7 45 33 34 45  0 34 33 30  0  0  0 45 45  0 45 33
 30  0 30  0 34 40 45  0 45 40 30 48 39 29  0 40 40 43  0 45 46 28]


In [0]:
res = ''.join([int_to_char[i] for i in preds])

In [0]:
print(text[:70]+res)

supposing that truth is a woman--what then? is there not ground for su ppositg thet thuth tn t poran -thit ihe   tt the e iot toewnd oor tuc


**CHARACTER LEVEL MODEL - V2**

In [0]:
import numpy as np
Tx = 50
X = []
for i in range(0, len(l1)-Tx, Tx):
  temp = []
  for j in range(i, i+Tx):
    temp.append(l1[j])
  X.append(temp)
X = np.array(X)

In [0]:
X.shape

(12017, 50)

In [0]:
Y = []
for i in range(Tx, len(l1)-Tx, Tx):
  temp = []
  temp.append(l1[i])
  Y.append(temp)
Y.append([8])  # adding a '.' at the end
Y = np.array(Y)
Y.shape

(12017, 1)

In [0]:
X[1]

array([43, 30,  0, 39, 40, 45,  0, 32, 43, 40, 46, 39, 29,  0, 31, 40, 43,
        0, 44, 46, 44, 41, 30, 28, 45, 34, 39, 32,  0, 45, 33, 26, 45,  0,
       26, 37, 37,  0, 41, 33, 34, 37, 40, 44, 40, 41, 33, 30, 43, 44])

In [0]:
Y[0]

array([43])

In [0]:
from keras.utils import to_categorical

Y = to_categorical(Y[:,:], num_classes = len(unique_chars))
#Y = Y.reshape((12017, 1, len(unique_chars)))
print(Y[0])
Y.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


(12017, 56)

**BUILDING MODEL**

In [0]:
import keras
from keras.layers import Dense, Dropout, LSTM, Activation, Input
from keras.models import Model
from keras.layers.embeddings import Embedding

In [0]:
embedding_layer = Embedding(len(unique_chars), 70, trainable = True, embeddings_initializer='uniform')
embedding_layer.build((None,))

In [0]:
def LSTM_model(input_shape):
    sentence_indices = Input(shape = input_shape, dtype = np.int32)
    embeddings = embedding_layer(sentence_indices)
    X = LSTM(700, return_sequences = True)(embeddings)
    X = Dropout(0.5)(X)
    X = LSTM(400, return_sequences = True)(X)
    X = Dropout(0.25)(X)
    X = LSTM(128, return_sequences = False)(X)
    X = Dense(len(unique_chars), activation = 'softmax')(X)
    
    model = Model(inputs = sentence_indices, outputs = X)
    
    return model

In [0]:
model = LSTM_model((50,))

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 50)                0         
_________________________________________________________________
embedding_3 (Embedding)      (None, 50, 70)            3920      
_________________________________________________________________
lstm_10 (LSTM)               (None, 50, 700)           2158800   
_________________________________________________________________
dropout_10 (Dropout)         (None, 50, 700)           0         
_________________________________________________________________
lstm_11 (LSTM)               (None, 50, 400)           1761600   
_________________________________________________________________
dropout_11 (Dropout)         (None, 50, 400)           0         
_________________________________________________________________
lstm_12 (LSTM)               (None, 128)               270848    
__________

In [0]:
from keras import optimizers
opt = optimizers.Adam(lr = 0.001)

model.compile(loss = 'categorical_crossentropy', optimizer = opt, metrics = ['accuracy'])

In [0]:
#model.load_weights('save8_95epochs.h5')
model.fit(X, Y, epochs = 20, batch_size = 128, shuffle = True)

Epoch 1/20
12017/12017 [==============================] - 46s 4ms/step - loss: 3.0448 - acc: 0.1702
Epoch 2/20
12017/12017 [==============================] - 44s 4ms/step - loss: 2.9718 - acc: 0.1715
Epoch 3/20
12017/12017 [==============================] - 44s 4ms/step - loss: 2.9702 - acc: 0.1717
Epoch 4/20
12017/12017 [==============================] - 44s 4ms/step - loss: 2.9688 - acc: 0.1717
Epoch 5/20
12017/12017 [==============================] - 44s 4ms/step - loss: 2.9694 - acc: 0.1717
Epoch 6/20
 2304/12017 [====>.........................] - ETA: 35s - loss: 2.9612 - acc: 0.1762